- name: "Install, run and collect sosreports"
  hosts: all
  remote_user: root
  gather_facts: off
  tasks:
    - name: "Install, run and collect sosreports"
      include_role:
        name: sosreport_gatherer
      vars:
        sosreport_gatherer_local_dir: /tmp/sosreports/
